#环境准备
before_script:
  - npm install --registry=https://registry.npm.taobao.org
  - GULP=./node_modules/.bin/gulp
  - $GULP clean

#构建
gulp_build:
  stage: build
  script:
    - $GULP
  tags:
    - node