#缓存
cache:
  paths:
    - node_modules/

#环境准备
before_script:
  - npm install --registry=https://registry.npm.taobao.org
  - GULP=./node_modules/.bin/gulp
  - $GULP clean

#构建
build:
  stage: build
  script:
    - $GULP
  tags:
    - node

#测试
test:
  stage: test
  script:
    - $GULP test
  tags:
    - node

#发布example网站
publish_example:
  stage: deploy
  script:
    - ssh eazyajax4js@bj.danwi.me 'cd eazyajax4js;git pull;dpm install;gulp'
    - ssh eazyajax4js@bj.danwi.me 'cd eazyajax4js/dist/example;forever stop eazyajax4js;forever start -a --uid "eazyajax4js" ./index.js'
  only:
    - develop
  tags:
    - linux

#发布到npm仓库
publish_npm:
  stage: deploy
  script:
    - $GULP
    - cd dist
    - npm publish
  only:
    - /^v\d+.\d+.\d+.*$/
  tags:
    - node